
print('wellcome to Quiz game')
answer=input('ARE YOU READY!(yes/no):')
if answer == 'yes':
    answer=input('You come to the first question\n'
          'Question 1:Truong sa island and Hoang sa island of Viet nam or china (Vietnam or china):')
    if answer =='Vietnam':
         print('correct')
    else:
        answer == 'china'
        print('incorrect\n'
              'Truong Sa and Hoang Sa islands belong to Vietnam')
answer = input('How many legs does a chicken walk on? (Two or Four)')
if answer == 'Two': 
             print('correct')
else:
            answer == 'Four'
            print('incorrect')
answer = input('1+2+4+5+6+7+8+9+10=(45 or 50):')
if answer =='45':
        print('correct')
else:
        answer =="50"
        print('incorrect')




